### ISSUE TITLE
Key-combo not working?

### ISSUE THREAD

**Issue by EliasL** [jbensmann/mouseless#42] opened 2023-11-16 13:05 UTC
Perhaps I have misunderstood something about the key-combo syntax, but I had thought that i could activate a layer holding down multiple keys like this: 

```
- name: initial
  bindings:
    leftmeta+leftalt: tap-hold-next leftmeta+leftalt; toggle-layer mouse ; 300
```
But I can't get that working. (Both leftmeta and leftalt work fine seperately)

**Comment by jbensmann** [comment] 2023-11-19 17:08
Unfortunately it is not possible to map a key-combo to something else (so one cannot put it on the left side of a colon).
But definitely something I will look into, so you can leave this issue open for reference.

**Comment by EliasL** [comment] 2023-11-19 18:40
Thanks! :)

**Comment by tmcelroy2202** [comment] 2024-04-26 16:23
Also interested in this! would love to remap ctrl+t to t for tridactyl.

**Comment by AnthonySmithDev** [comment] 2024-06-17 21:03
Why doesn't this work?

    r: tap-hold r ; leftmeta+leftctrl ; 150
    e: tap-hold e ; leftmeta+leftalt ; 150

**Comment by jbensmann** [comment] 2024-10-19 15:43
It is now possible to map a key combo (but currently limited to 2 keys), e.g. `leftalt+leftmeta: toggle-layer mouse`.

The combo is activated when the two keys are pressed simultaneously, the maximum duration between the presses is defined in the new config option `comboTime` (e.g. `comboTime: 25` for 25 ms).

However it does not work in combination with `tap-hold`, but maybe it is also not necessary for this use case.

**Comment by tmcelroy2202** [comment] 2024-10-21 00:31
Trying this out now, defined in my config I have 

layers:
- name: initial
  bindings:
    leftalt: tap-hold leftalt ; toggle-layer mouse ; 300
    leftctrl+t: t
    leftctrl+leftalt: t
    esc: capslock
    capslock: esc

leftctrl+leftalt does type a t
leftctrl+t sends ctrl t and does not type a t 

am I doing something wrong, or are only modifier keys supported for this right now ? 

I would like for leftctrl+t to not send ctrl + t but to just send t. im trying to stop using the tabs in firefox and use the native tab control in tridactyl.

**Comment by jbensmann** [comment] 2024-10-21 18:46
The problem is that the two keys have to be pressed (nearly) simultaneously, so it probably does not fit your use case.

There also currently is no other good way to do that.
One could make `leftctrl` toggle another layer with two bindings `t: t` and `_: leftctrl+_`, but then loses the ability to hold down `leftctrl` on its own.

**Comment by tmcelroy2202** [comment] 2024-10-21 23:41
That does work for pressing t on ctrl + t and allowing passthrough of ctrl + whatever, but I do use ctrl + scroll on trackpad to zoom in on obsidian excalidraw, and it is much nicer than repeatedly hitting ctrl +. 

I increased comboTime to 200 and that works fine. scrolling in obsidian is noticeably higher latency, but i'll cope with that. 

Thanks for implementing this!

**Comment by jbensmann** [comment] 2024-10-26 08:02
Good to hear it works for you.

There is also issue #48 which I think is exactly your use case.
There will probably be a solution for that, but I am not sure yet how it will look.

So I am closing this issue.

**Closed by jbensmann** 2024-10-26 08:02 UTC
