### ISSUE TITLE
Mouseless don't respect palm rejection setting

### ISSUE THREAD

**Issue by czhang03** [jbensmann/mouseless#54] opened 2024-04-04 20:47 UTC
On most desktop on linux, palm rejection is enabled by default. However, mouseless doesn't respect this setting:

To reproduce, on a gnome desktop set `/org/gnome/desktop/peripherals/touchpad/disable-while-typing` to true in dconf. 
Try to type and moving the trackpad at the same time with mouseless enabled will see the mouse cursor moves normally; if the mouseless service is disabled, then the trackpad input will be ignored when the keyboard is typing.

**Comment by jbensmann** [comment] 2024-06-16 15:49
I think this is a duplicate of #50, so I will close this one.

In the other issue I linked a possible solution, I don't know if there is a way to fix this in mouseless directly as it creates a virtual keyboard device, which is treated like an external keyboard by default.

**Closed by jbensmann** 2024-06-16 15:49 UTC
